name: My First GitHub Actions  # Name of the workflow

on: [push]  # Trigger this workflow on push events

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    strategy:
      matrix:
        python-version: [3.8, 3.9]  # Test multiple Python versions

    steps:
    - uses: actions/checkout@v4  # Checkout the repository code

    - name: Set up Python  # Install Python based on the matrix
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies  # Install required Python packages
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests  # Run tests using pytest
      run: |
        cd src  # Navigate to the source directory
        python -m pytest addition.py

    - name: Debug Python Setup  # Print Python version and path
      run: |
        python --version
        which python
